site_name: SAHD
site_description: >-
    Semantics of Ancient Hebrew Database
site_url: 'https://pthu.github.io/sahd/'
site_author: Vesa Åkerman

nav:
    - Home: index.md
    - Lemmas:
            - א:
                - אדם - to be red: words/2-d-m.md
                - אָדֹם - red: words/2adom.md
                - אוּרִים וְתֻמִּים - Urim Thummim: words/2urim_wthummim.md
                - אָזֵן - equipment: words/2azen.md
                - אַח - brazier: words/2ach.md
                - אָמָה - female servant: words/2amah.md
                - אַמְתַּחַת - sack: words/2amthachath.md
                - אַרְגְּוָן - bright purple: words/2argwan.md
                - אַרְגַּז - box: words/2argaz.md
                - אַרְגָּמָן - bright purple: words/2argaman.md
                - ארר - to curse: words/2-r-r.md
            - ב:
                - בַּד - pole: words/bad_2.md
                - בֶּקַע - beka: words/beqa3.md
                - בָּרָד - hail: words/barad.md
                - בְּרִית - covenant: words/brith.md
                - ברך - to bless: words/b-r-k_2.md
                - בְּרָכָה - blessing: words/brakah.md
            - ג:
                - גְּאוּלִים - redemption: words/g2ulim.md
                - גאל - to redeem: words/g-2-l.md
                - גְּאֻלָּה - redemption, right of: words/g2ullah.md
                - גֻּלָּה - bowl: words/gullah.md
                - גִּלָּיוֹן - mirror: words/gillayon.md
            - ד:
                - דֶּרֶךְ - road, way: words/derek.md
            - ה:
                - הֲדֹם - footstool: words/hadom.md
            - ו:
                - וָו - hook: words/waw.md
            - ז:
                - זִיק - fiery missile: words/ziq.md
            - ח:
                - חוּם - dark brown: words/chum.md
                - חוֹתָם - seal: words/chotam.md
                - חֹזֶה - (court) diviner: words/chozeh.md
                - חֶסֶד - faithfulness: words/chesed.md
                - חֶרֶט - burin: words/cheret.md
                - חַשְׁמַן - amethyst(?): words/chashman.md
            - ט:
                - טַבַּעַת - ring: words/tabba3at.md
                - טוה - to spin, twist: words/t-w-h.md
            - י:
                - יָקוּד - glowing fire: words/yaqud.md
                - יְשׁוּעָה - protection: words/yshu3ah.md
                - ישׁע - to save, help: words/y-sh-3.md
                - יֵשַׁע - safety: words/yesha3.md
            - כ:
                - כִּבְשָׁן - kiln: words/kibshan.md
                - כִּיר - cooking-stove: words/kir.md
                - כְּלִי - vessel: words/kli.md
                - כִּסֵּא - throne: words/kisse2.md
                - כַּר - saddle: words/kar_1.md
                - כְּרוּב - cherub: words/krub.md
                - כַּרְמִיל - bright, rich red: words/karmil.md
            - ל:
                - לָבָן - white: words/laban.md
                - לוּחַ - board: words/luach.md
                - לַפִּּיד - cresset, torch: words/lappid.md
            - מ:
                - מָאוֹר - light: words/ma2or.md
                - מְגִלָּה - scroll: words/mgillah.md
                - מוֹט - pole: words/mot.md
                - מוֹשָׁעָה - deliverance: words/mosha3ah.md
                - מְזַמֶּרֶת - trimming knife (?): words/mzammereth.md
                - מַחֲבַת - griddle: words/machabath.md
                - מְחוּגָה - callipers: words/mchugah.md
                - מַחֲרֵשָׁה/מַחֲרֶשֶׁת - plough: words/machareshah.md
                - מִכְבָּר - grating: words/mikbar.md
                - מֶלְקָחַיִם - forceps: words/melqachayim.md
                - מְנוֹרָה - lampstand: words/mnorah.md
                - מַפְרֶקֶת - neck: words/mapreqeth.md
                - מַפְתֵּחַ - key: words/maptheach.md
                - מַקֵּל - branch, staff: words/maqqel.md
                - מַרְאָה - vision, mirror: words/mar2ah.md
                - מֶשֶׁךְ - bag: words/meshek_1.md
                - מִשְׁפְּתַיִם/שְׁפַתַּיִם - sack: words/mishpthayim.md
            - נ:
                - נָבִיא/נְבִיאָה - prophet(ess): words/nabi2.md
                - נחם - to comfort: words/n-ch-m.md
                - נִיר - lamp: words/nir_1.md
                - נֵר - lamp: words/ner_1.md
                - נִשְׁתְּוָן - official letter: words/nishthwan.md
            - ס:
                - סָעִיף - cleft: words/sa3ip.md
                - סֵפֶר - book: words/seper.md
                - סִפְרָה - book: words/siprah.md
            - ע:
                - עֶבֶד - servant, slave: words/3ebed.md
                - עֲבֹדָה - service: words/3abodah.md
                - עֶזְרָה - help: words/3ezrah.md
                - עֵט - stylus: words/3et.md
                - עֲטָרָה - wreath, crown: words/3atarah.md
            - פ:
                - פדה - to liberate: words/p-d-h.md
                - פְּדוּיִם - redemption price: words/pduyim.md
                - פְּדוּת - redemption-action: words/pduth.md
                - פִּדְיוֹן - ransom: words/pidyon.md
                - פֶּלֶךְ - spindle: words/pelek.md
                - פרק - to pull off: words/p-r-q.md
                - פָּרָק - piece of meat: words/paraq.md
                - פֶּרֶק - plunder: words/pereq.md
                - פִּשְׁתָּה - wick: words/pishthah.md
            - צ:
                - צלה - to roast: words/ts-l-h.md
                - צִפֹּרֶן - nail: words/tsipporen.md
                - צְרוֹר - pouch: words/tsror_1.md
            - ק:
                - קבב - to curse: words/q-b-b.md
                - קַלַּחַת - stewpot: words/qallachath.md
                - קֶסֶת - inkpot(?): words/qeseth.md
            - ר:
                - רֹאֶה - seer: words/ro2eh.md
                - רְאִי - mirror: words/r2i.md
            - שׂ:
                - שֶׂרֶד - scriber: words/cered.md
            - שׁ:
                - שׁוֹעַ - great man: words/shoa3.md
                - שׁוּעַ - cry for help: words/shua3.md
                - שֶׁלֶג - snow: words/sheleg.md
                - שָׁנִי - bright red dye: words/shani_1.md
                - שִׁפְחָה - maidservant: words/shipchah.md
                - שַׁרְבִיט - sceptre: words/sharbit.md
            - ת:
                - תְּבוּנָה - understanding: words/thbunah.md
                - תְּכֵלֶת - bluish purple: words/thkeleth.md
                - תִּפְלָה - senselessness: words/thiplah.md
                - תְּשׁוּעָה - deliverance, state of: words/thshu3ah.md
    - Semantic fields:
            - Agriculture: semantic_fields/agriculture.md
            - Benevolence: semantic_fields/benevolence.md
            - Blessing: semantic_fields/blessing.md
            - Cloth: semantic_fields/cloth.md
            - Colours: semantic_fields/colours.md
            - Commitment: semantic_fields/commitment.md
            - Craft: semantic_fields/craft.md
            - Cult: semantic_fields/cult.md
            - Cursing: semantic_fields/cursing.md
            - Deliverance: semantic_fields/deliverance.md
            - Divination: semantic_fields/divination.md
            - Food Preparation: semantic_fields/food preparation.md
            - Gemstones: semantic_fields/gemstones.md
            - Headdress: semantic_fields/headdress.md
            - Honour: semantic_fields/honour.md
            - Kingship: semantic_fields/kingship.md
            - Knowledge: semantic_fields/knowledge.md
            - Light: semantic_fields/light.md
            - Metals: semantic_fields/metals.md
            - Morality: semantic_fields/morality.md
            - Servitude: semantic_fields/servitude.md
            - Supernatural Beings: semantic_fields/supernatural beings.md
            - Textile Production: semantic_fields/textile production.md
            - Transport: semantic_fields/transport.md
            - Tribute: semantic_fields/tribute.md
            - Utensils: semantic_fields/utensils.md
            - Weather: semantic_fields/weather.md
            - Weight: semantic_fields/weight.md
            - Writing: semantic_fields/writing.md
    - News: 'store/news.md'
    - Contributors:
            - James K. Aitken: contributors/james_k._aitken.md
            - Bob Becking: contributors/bob_becking.md
            - Panc C. Beentjes: contributors/panc_c._beentjes.md
            - W.A.M. Beuken: contributors/w.a.m._beuken.md
            - Benjamin M. Bogerd: contributors/benjamin_m._bogerd.md
            - Graham I. Davies: contributors/graham_i._davies.md
            - Raymond de Hoop: contributors/raymond_de_hoop.md
            - Johannes C. de Moor: contributors/johannes_c._de_moor.md
            - Kees den Hertog: contributors/kees_den_hertog.md
            - Karel Deurloo: contributors/karel_deurloo.md
            - Meindert Dijkstra: contributors/meindert_dijkstra.md
            - Alison Gray: contributors/alison_gray.md
            - John E. Hartley: contributors/john_e._hartley.md
            - Cornelis Houtman: contributors/cornelis_houtman.md
            - Konrad D. Jenner: contributors/konrad_d._jenner.md
            - Marjo Korpel: contributors/marjo_korpel.md
            - M.D. Koster: contributors/m.d._koster.md
            - Eric Peels: contributors/eric_peels.md
            - Kurtis Peters: contributors/kurtis_peters.md
            - Jakub M. Pogonowski: contributors/jakub_m._pogonowski.md
            - Alison Salvesen: contributors/alison_salvesen.md
            - Paul Sanders: contributors/paul_sanders.md
            - M. Patrizia Sciumbata: contributors/m._patrizia_sciumbata.md
            - Haposan Cornelius Sinaga: contributors/haposan_cornelius_sinaga.md
            - Klaas A. D. Smelik: contributors/klaas_a._d._smelik.md
            - Willem Smelik: contributors/willem_smelik.md
            - Chiara Stornaiuolo: contributors/chiara_stornaiuolo.md
            - T. Jonathan Stökl: contributors/t._jonathan_stökl.md
            - Michaël N. van der Meer: contributors/michaël_n._van_der_meer.md
            - Jacques T.A.G.M. van Ruiten: contributors/jacques_t.a.g.m._van_ruiten.md
            - Archibald L.H.M. van Wieringen: contributors/archibald_l.h.m._van_wieringen.md
            - Bertus van ’t Veld: contributors/bertus_van_’t_veld.md
            - Klaas R. Veenhof: contributors/klaas_r._veenhof.md
            - Geert Jan Veldman: contributors/geert_jan_veldman.md
            - Arian Verheij: contributors/arian_verheij.md
            - Alice Wood: contributors/alice_wood.md
    - Editorial board:
            - Marilyn Burton: editorial_board/marilyn_burton.md
            - Raymond de Hoop: editorial_board/raymond_de_hoop.md
            - Marjo Korpel: editorial_board/marjo_korpel.md
            - Alessandra Pecchioli: editorial_board/alessandra_pecchioli.md
            - Kurtis Peters: editorial_board/kurtis_peters.md
            - Paul Sanders: editorial_board/paul_sanders.md
            - Willem Smelik: editorial_board/willem_smelik.md
            - Chiara Stornaiuolo: editorial_board/chiara_stornaiuolo.md
            - T. Jonathan Stökl: editorial_board/t._jonathan_stökl.md
            - Michaël N. van der Meer: editorial_board/michaël_n._van_der_meer.md
            - Willem van Peursen: editorial_board/willem_van_peursen.md
    - Printed publications: 'store/printed_publications.md'
    - Miscellaneous:
            - Overview Deliverance: miscellaneous/overview_deliverance.md
    - Partners: 'store/partners.md'
    - Contribution: 'store/contribution.md'
    - Contact: 'store/contact.md'
    - Abbreviations: 'store/abbreviations.md'

theme:
    name: material
    custom_dir: overrides

markdown_extensions:
    - attr_list
    - footnotes
    - md_in_html

extra_css:
   - static/stylesheets/extra.css

extra_javascript:
    - static/javascripts/extra.js
    - static/javascripts/goatcounter.js


